DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS events;

CREATE TABLE users
(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
username VARCHAR UNIQUE,
password VARCHAR NOT NULL
);

CREATE TABLE events
(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR UNIQUE,
day INTEGER NOT NULL,
month INTEGER NOT NULL,
year INTEGER NOT NULL,
type VARCHAR NOT NULL
);

INSERT INTO users VALUES(NULL,'mieic', 'mieic13feup');
INSERT INTO users VALUES(NULL,'Contador', 'Baiao');
INSERT INTO users VALUES(NULL,'F0lha', 'Castro');
INSERT INTO users VALUES(NULL,'revtut', 'mau');

