DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS events;

CREATE TABLE users
(
id INTEGER PRIMARY KEY,
username VARCHAR UNIQUE,
password VARCHAR NOT NULL
);

CREATE TABLE events
(
id INTEGER  PRIMARY KEY,
name VARCHAR UNIQUE,
day INTEGER NOT NULL,
month INTEGER NOT NULL,
year INTEGER NOT NULL,
type VARCHAR NOT NULL
);

INSERT INTO users VALUES(1,'mieic', 'mieic13feup');
INSERT INTO users VALUES(2,'Contador', 'Baiao');
INSERT INTO users VALUES(3,'F0lha', 'Castro');
INSERT INTO users VALUES(4,'revtut', 'mau');

